apiVersion: v1
kind: Service
metadata:
  name: currency
  namespace: app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  type: LoadBalancer  # Use LoadBalancer
  selector:
    app: currency
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080