apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  namespace: app
  labels:
    app: currency
spec:
  replicas: 3
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
      - name: currency
        image: techwithprerit/k8s-hindi-app1:1.2-major
        ports:
        - containerPort: 80
